version: '3'
services:
  brain-agriculture-postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: brain-agriculture
      POSTGRES_PASSWORD: brain-agriculture
      POSTGRES_DB: brain-agriculture
    volumes:
      - ./data:/var/lib/postgresql/data
  brain-agriculture-redis:
    image: redis:latest
    restart: always
    container_name: 'redis'
    command: redis-server --requirepass c77N7DKtuXQmLaITT81Aee3f --maxmemory 2048mb --maxmemory-policy allkeys-lru
    ports:
      - '6379:6379'
    networks:
      - network
networks:
  network:
    driver: bridge
